#Copies golang binary and schedule it through cron
FROM alpine:latest

COPY pricing-reporting /usr/local/bin/

RUN echo "15 * * * * /usr/local/bin/pricing-reporting" > /etc/crontabs/root

CMD ["/usr/sbin/crond", "-f", "-d", "0"]
