x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '2.0.5'
  publishedVersionMetadata:
    releaseNote: >-
      Initial Release of VVDN Intelligent Cloud Engine
    releaseTypes:
      - Feature
    recommended: false

  images:
    node:
      properties:
        node.statefulSet.image:
          type: FULL
        AppVersion:
          type: TAG
  clusterConstraints:
    resources:
    - replicas: 6
      requests:
        memory: 16Gi
        cpu: 4

properties:
  name:                   
    type: string
    x-google-marketplace:
      type: NAME
  namespace:              
    type: string
    default: default
    x-google-marketplace:
      type: NAMESPACE
  coapTransport:
    type: boolean
    default: false
    title: Deploys COAP transport service
    description: Tick this if you want to deploy coap transport service
  lwm2mTransport:
    type: boolean
    default: false
    title: Deploys lwm2m transport service
    description: Tick this if you want to deploy lwm2m transport service
  mqttTransport:
    type: boolean
    default: false
    title: Deploys mqtt transport service
    description: Tick this if you want to deploy mqtt transport service
  snmpTransport:
    type: boolean
    default: false
    title: Deploys snmp transport service
    description: Tick this if you want to deploy snmp transport service
  ingress.enabled:
    type: boolean
    default: true
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  httpsIngress:
    type: boolean
    default: false
    title: Ticking this will add https Ingress.
    description: For this to work you must be having your domain name added in CloudDNS.
  https_ingress.ManagedCertificate.domains:
    type: string
    title: Domain name to add for LoadBalancer if you tick above box.
    description: Provide a domain name for https LoadBalancer, if you choose to go with http LoadBalancer add 'nil' here.
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET


required:
- name
- namespace
- coapTransport
- lwm2mTransport
- mqttTransport
- snmpTransport
- httpsIngress
- https_ingress.ManagedCertificate.domains