{{- if .Values.httpsIngress }}
{{- if ne .Values.https_ingress.domain "nil" }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.https_ingress.ManagedCertificate.name }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  domains:
  - {{ .Values.https_ingress.domain }}
{{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.https_ingress.FrontendConfig.name}}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  redirectToHttps:
    enabled: {{ .Values.https_ingress.FrontendConfig.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.https_ingress.name }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  namespace: {{ .Values.namespace }}
  annotations: 
    {{- if ne .Values.https_ingress.domain "nil" }}
    networking.gke.io/managed-certificates: {{ .Values.https_ingress.ManagedCertificate.name }}
    {{- end }}
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.https_ingress.FrontendConfig.name}}
    {{- if ne .Values.staticip "nil" }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticip }}
    {{- end }}
spec:
  rules:
    {{- if ne .Values.https_ingress.domain "nil" }}
    - host: {{ .Values.https_ingress.domain }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
        {{- range .Values.https_ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
        {{- end }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.http_ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations: 
    {{- if ne .Values.staticip "nil" }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticip }}
    {{- end }}
spec:
  rules:
    {{- if ne .Values.https_ingress.domain "nil" }}
    - host: {{ .Values.https_ingress.domain }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
        {{- range .Values.http_ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
        {{- end }}
{{ end }}