apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pricing-reporting
  name: pricing-reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-reporting
  template:
    metadata:
      labels:
        app: pricing-reporting
    spec:
      restartPolicy: Always
      containers:
      - name: reporting-container
        imagePullPolicy: Always
        image: {{ .Values.reporting_deployment.image }}
        readinessProbe:
          exec:
            command: ["psql", "-h", "postgres", "-p", "5432", "-d", "vvdn-ice-test", "-U", "postgres", "-c", "\\dt"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3 
        env:
        - name: AGENT_CONSUMER_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportingSecret }}
              key: consumer-id
        - name: PGHOST
          value: postgres
        - name: PGDATABASE
          value: vvdn-ice-test
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: vvdnicon
        - name: PGPORT
          value: "5432"
      - name: http-status
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0 
        env:
        - name: PGHOST
          value: postgres
        - name: PGDATABASE
          value: vvdn-ice-test
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: vvdnicon
        - name: PGPORT
          value: "5432"
      - name: ubbagent
        image: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest 
        env:
        - name: AGENT_CONFIG_FILE
          value: "/etc/ubbagent/config.yaml"
        - name: AGENT_LOCAL_PORT
          value: "4567"
        - name: AGENT_ENCODED_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportingSecret }}
              key: reporting-key
        - name: AGENT_CONSUMER_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportingSecret }}
              key: consumer-id
        volumeMounts:
        - name: ubbagent-config
          mountPath: /etc/ubbagent
      volumes:
      - name: ubbagent-config
        configMap:
          name: {{ .Release.Name }}-ubbagent-config

---

apiVersion: v1
kind: Service
metadata:
  name: pricing-reporting
spec: 
  type: ClusterIP
  selector:
    app: pricing-reporting
  ports:
  - port: 8080
    targetPort: 8080
