apiVersion: batch/v1
kind: CronJob
metadata:
  name: publish-report
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.reporting_cronjob.restartPolicy }}
          containers:
          - image: {{ .Values.reporting_cronjob.image }}
            imagePullPolicy: {{ .Values.reporting_cronjob.imagePullPolicy }}
            name: send-dummy-report
            env:
            - name: PGHOST
              value: {{ .Values.reporting_cronjob.pghost | quote }}
            - name: PGDATABASE
              value: {{ .Values.reporting_cronjob.pgdatabase | quote }}
            - name: PGUSER
              value: {{ .Values.reporting_cronjob.pguser | quote }}
            - name: PGPASSWORD
              value: {{ .Values.reporting_cronjob.pgpassword | quote}}
            - name: PGPORT
              value: {{ .Values.reporting_cronjob.pgport | quote }}
          - name: ubbagent
            image: {{ .Values.reporting_cronjob.sidecarImage }}
            env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: autogenerated-reporting-secret
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: autogenerated-reporting-secret
                  key: consumer-id
            volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
          volumes:
          - name: ubbagent-config
            configMap:
              name: {{ .Release.Name }}-ubbagent-config