apiVersion: batch/v1
kind: CronJob
metadata:
  name: publish-report
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.reporting_cronjob.restartPolicy }}
          containers:
          - image: {{ .Values.reporting_cronjob.image }}
            imagePullPolicy: {{ .Values.reporting_cronjob.imagePullPolicy }}
            name: {{ .Values.reporting_cronjob.name }}
            env:
            - name: {{ .Values.reporting_cronjob.pghost }}
              value: {{ .Values.reporting_cronjob.value1 | quote }}
            - name: {{ .Values.reporting_cronjob.pgdatabase }}
              value: {{ .Values.reporting_cronjob.value2 | quote }}
            - name: {{ .Values.reporting_cronjob.pguser }}
              value: {{ .Values.reporting_cronjob.value3 | quote }}
            - name: {{ .Values.reporting_cronjob.pgpassword }}
              value: {{ .Values.reporting_cronjob.value4 }}
            - name: {{ .Values.reporting_cronjob.pgport }}
              value: {{ .Values.reporting_cronjob.value5 | quote }}
          - name: {{ .Values.reporting_cronjob.name2 }}
            image: {{ .Values.reporting_cronjob.sidecarImage }}
            env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: fake-reporting-secret
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: fake-reporting-secret
                  key: consumer-id
            volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
          volumes:
          - name: ubbagent-config
            configMap:
              # name: {{.Values.name}}-ubbagent-config
              name: test-deployment-ubbagent-config