apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tb_http_transport.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.tb_http_transport.configmap.labels }}
    app.kubernetes.io/name: "{{ .Release.Name }}"
data:
  conf:
    {{- .Values.tb_http_transport.configmap.conf | toYaml | indent 2 }}
  logback:
    {{- .Values.tb_http_transport.configmap.logback | toYaml | indent 2 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.tb_http_transport.statefulset.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  serviceName: {{ .Values.tb_http_transport.statefulset.serviceName | quote }}
  podManagementPolicy: {{ .Values.tb_http_transport.statefulset.podManagementPolicy }}
  replicas: {{ .Values.tb_http_transport.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tb_http_transport.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tb_http_transport.statefulset.name }}
    spec:
      volumes:
        - name: {{ .Values.tb_http_transport.statefulset.volumesName }}
          configMap:
            name: {{ .Values.tb_http_transport.configmap.name }}
            items:
            {{- range .Values.tb_http_transport.statefulset.items }}
            - key: {{ .key }}
              path: {{ .path }}
            {{- end }}
      containers:
        - name: {{ .Values.tb_http_transport.statefulset.containerName }}
          imagePullPolicy: {{ .Values.tb_http_transport.statefulset.imagePullPolicy }}
          image: {{ .Values.tb_http_transport.statefulset.image }}
          ports:
            {{- range .Values.tb_http_transport.statefulset.containerPorts }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.tb_http_transport.statefulset.resources.limitscpu | quote }}
              memory: {{ .Values.tb_http_transport.statefulset.resources.limitsmemory }}
            requests:
              cpu: {{ .Values.tb_http_transport.statefulset.resources.requestscpu | quote }}
              memory: {{ .Values.tb_http_transport.statefulset.resources.requestsmemory }}
          env:
            - name: {{ .Values.tb_http_transport.statefulset.envName }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.tb_http_transport.statefulset.fieldPath }}
          {{- include "helpers.list-env-tb-http-transport" . | indent 7 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.kafka.configmap1.name }}
            - configMapRef:
                name: {{ .Values.redis.configmap.name }}
          volumeMounts:
            {{- range .Values.tb_http_transport.statefulset.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
          readinessProbe:
            periodSeconds: {{ .Values.tb_http_transport.statefulset.readinessProbeperiodSeconds }}
            tcpSocket:
              port: {{ .Values.tb_http_transport.statefulset.readinessProbetcpSocketport }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.tb_http_transport.statefulset.livenessProbeinitialDelaySeconds }}
            periodSeconds: {{ .Values.tb_http_transport.statefulset.livenessProbeperiodSeconds }}
            tcpSocket:
              port: {{ .Values.tb_http_transport.statefulset.livenessProbetcpSocketport }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tb_http_transport.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    cloud.google.com/backend-config: '{"default": "http-backend-config"}'
spec:
  type: {{ .Values.tb_http_transport.service.type }}
  selector:
    app: {{ .Values.tb_http_transport.statefulset.name }}
  ports:
    {{- range .Values.tb_http_transport.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
    {{- end }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  healthCheck:
    type: {{ .Values.tb_http_transport.BackendConfig.healthChecktype }}
    requestPath: {{ .Values.tb_http_transport.BackendConfig.healthCheckrequestPath }}
    port: {{ .Values.tb_http_transport.BackendConfig.healthCheckPort }}