{{- if .Values.snmpTransport }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tb_snmp_transport.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.tb_snmp_transport.configmap.labels }}
    app.kubernetes.io/name: "{{ .Release.Name }}"
data:
  conf: 
    {{- .Values.tb_snmp_transport.configmap.conf | toYaml | indent 2 }}
  logback: 
    {{- .Values.tb_snmp_transport.configmap.logback | toYaml | indent 2 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.tb_snmp_transport.statefulset.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  serviceName: {{ .Values.tb_snmp_transport.statefulset.serviceName | quote }}
  podManagementPolicy: {{ .Values.tb_snmp_transport.statefulset.podManagementPolicy }}
  replicas: {{ .Values.tb_snmp_transport.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tb_snmp_transport.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tb_snmp_transport.statefulset.name }}
    spec:
      volumes:
        - name: {{ .Values.tb_snmp_transport.statefulset.volumesName }}
          configMap:
            name: {{ .Values.tb_snmp_transport.configmap.name }}
            items:
            {{- range .Values.tb_snmp_transport.statefulset.items }}
              - key: {{ .key }}
                path: {{ .path }}
            {{- end }}
      containers:
        - name: {{ .Values.tb_snmp_transport.statefulset.containerName }}
          imagePullPolicy: {{ .Values.tb_snmp_transport.statefulset.imagePullPolicy }}
          image: {{ .Values.tb_snmp_transport.statefulset.image }}
          resources:
            limits:
              cpu: {{ .Values.tb_snmp_transport.statefulset.resources.limitscpu | quote }}
              memory: {{ .Values.tb_snmp_transport.statefulset.resources.limitsmemory }}
            requests:
              cpu: {{ .Values.tb_snmp_transport.statefulset.resources.requestscpu | quote }}
              memory: {{ .Values.tb_snmp_transport.statefulset.resources.requestsmemory }}
          env:
            - name: {{ .Values.tb_snmp_transport.statefulset.envName }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.tb_snmp_transport.statefulset.fieldPath }}
          {{- include "helpers.list-env-tb-snmp-transport" . | indent 7 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.kafka.configmap1.name }}
          volumeMounts:
            {{- range .Values.tb_snmp_transport.statefulset.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
{{ end }}